fragment PostParts on Post {
  __typename
  title
  excerpt
  date
  category
  tags
  author
  companionSlug
  linkedInUrl
  featured
  body
}

fragment AuthorParts on Author {
  __typename
  name
  role
  initials
  color
  photo
  linkedInUrl
  bio
  body
}

fragment HomePageParts on HomePage {
  __typename
  heroBadgeText
  heroHeadline
  heroHeadlineAccent
  heroSubtext
  heroPrimaryButtonText
  heroPrimaryButtonHref
  heroSecondaryButtonText
  heroSecondaryButtonHref
  startHereLabel
  startHereHeading
  startHereCards {
    __typename
    label
    description
    href
    colorClass
  }
  featuredSectionLabel
  featuredSectionHeading
  postTypesSectionLabel
  postTypesSectionHeading
  postTypeCards {
    __typename
    label
    description
    href
    className
  }
  foundersSectionLabel
  foundersSectionHeading
  foundersSectionText
  foundersButtonText
  foundersButtonHref
  latestSectionLabel
  latestSectionHeading
  latestSectionText
  followSectionLabel
  followSectionHeading
  followSectionText
  followButtonText
}

fragment AboutPageParts on AboutPage {
  __typename
  seoTitle
  seoDescription
  sectionLabel
  headline
  headlineAccent
  intro
  pointOfViewLabel
  pointOfViewText
  primaryButtonText
  primaryButtonHref
  secondaryButtonText
  peopleSectionLabel
  peopleSectionHeading
  body
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  siteTagline
  linkedInUrl
  betaBadge
  navItems {
    __typename
    label
    href
  }
  siteMetaTitle
  siteMetaDescription
}

fragment NewsletterCTAParts on NewsletterCTA {
  __typename
  badgeText
  headline
  subtext
  emailPlaceholder
  buttonText
  successMessage
  linkedInNudge
}

fragment FooterParts on Footer {
  __typename
  brandTagline
  staySectionLabel
  staySectionText
  linkedInButtonText
  copyrightSuffix
  builtByLine
}
